# Generated by Django 4.2.21 on 2025-05-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

	initial = True

	dependencies = [
	]

	operations = [
		migrations.CreateModel(
			name='BookFilter',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('filter', models.JSONField(blank=True, null=True)),
			],
		),
	]
