# Generated by Django 4.2.21 on 2025-05-15 14:05

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

	dependencies = [
		('app', '0001_initial'),
	]

	operations = [
		migrations.CreateModel(
			name='Author',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('name', models.CharField(max_length=300)),
			],
		),
		migrations.CreateModel(
			name='Book',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('title', models.CharField(max_length=200)),
				('keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None)),
				('is_published', models.BooleanField()),
				('published_at', models.DateField(blank=True, null=True)),
				('pages_count', models.PositiveBigIntegerField()),
				('genre', models.CharField(choices=[('FANTASY', 'Фантастика'), ('PROSE', 'Проза'), ('FABLE', 'Басня')], max_length=50)),
				('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.author')),
			],
		),
	]
