# Generated by Django 4.2.21 on 2025-06-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		('app', '0002_author_book'),
	]

	operations = [
		migrations.AddField(
			model_name='book',
			name='note',
			field=models.TextField(blank=True, null=True),
		),
	]
