# Generated by Django 4.2.21 on 2025-06-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		('app', '0003_book_note'),
	]

	operations = [
		migrations.AddField(
			model_name='book',
			name='public_uuid',
			field=models.UUIDField(blank=True, null=True),
		),
	]
